#!/bin/sh
set -e

files="rc_freebsd.times rc_rcpar.times"
n=60

for file in $files; do
    touch $file
    name=`echo $file | cut -f1 -d'.'`
    lines=`cat $file | wc -l`
    if [ $lines -lt $n ]; then
        echo "$name $lines"
        cp $name /etc/rc
        reboot
    fi
done

echo "Amostras coletadas com sucesso"
