#!/bin/sh
set -e

files="rc_freebsd.times rc_rcpar.times"
z=$1
e=$2
N=$3
S=$4
T=`echo "$N * $S" | bc -l`

for file in $files; do
    touch $file
    name=`echo $file | cut -f1 -d'.'`
    lines=`cat $file | wc -l`
    if [ $lines -lt $T ]; then
        echo "$name $lines"
        cp $name /etc/rc
        reboot
    fi
done

sed -i -- "s:~/collect.*::g" ~/.cshrc

for file in $files; do
    name=`echo $file | cut -f1 -d'.'`
    echo "Grupo: $name"
    calc_stats $z $e $N $file
done
