#!/bin/sh
set -e

files="rc_freebsd.times rc_rcpar.times"
z=1.96
e=0.05
N=0
S=10
tmp=0
n1=10

for file in $files; do
    touch $file
    name=`echo $file | cut -f1 -d'.'`
    lines=`cat $file | wc -l`
    if [ $lines -lt $n1 ]; then
        echo "$name $lines"
        cp $name /etc/rc
        reboot
    else
        tmp=`calc_stats "$z" "$e" "$n1" "$file" | awk 'END{print $5}'`
        echo "Grupo: $name"
        calc_stats $z $e $n1 $file
        echo
        if [ $tmp -gt $N ]; then
            N=$tmp
        fi
    fi
done

echo "Serão coletadas $S amostras de tamanho $N por grupo."
echo "Deseja iniciar o processo? (s/n)"
read ans
case $ans in
    [Ss]*)
        for file in $files; do
            name=`echo $file | cut -f1 -d'.'`
            mv $name.times $name.warmup
        done

        sed -i -- "s:~/warmup:~/collect $z $e $N $S:g" ~/.cshrc
        reboot
        ;;
esac
